### PR TITLE
Create a fm.common.BaseEncoding (in java) that wraps the guava BaseEncoding to avoid proguard issues

### PR DESCRIPTION
**Pull request by er1c**

### CODE REVIEW

**Comment by tpunder** [comment]
Before your change:
```
scala> fm.common.UUID.main(Array("true"))
...
Total Time: 7715ms, total UUIDs Created: 80000000, per ms: 10369
```


After your change:
```
scala> fm.common.UUID.main(Array("true"))
...
Total Time: 11560ms, total UUIDs Created: 80000000, per ms: 6920
```

**Comment by er1c** [comment]
Updated approach to create a fm.common.BaseEncoding that is a .java wrapper for the guava BaseEncoding that gets around the proguard issues.  Big performance increase on the change...

Timing stats for my machine:

scala> fm.common.UUID.main(Array("true"))

Before:
Total Time: 11850ms, total UUIDs Created: 80000000, per ms: 6751
Started at: Sat Jan 23 12:10:09 PST 2016
  Ended at: Sat Jan 23 12:10:22 PST 2016
Total Time: 12 seconds (0.2 minutes) (0.0 hours)


After:
Total Time: 1836ms, total UUIDs Created: 80000000, per ms: 43572
Started at: Sat Jan 23 12:07:19 PST 2016
  Ended at: Sat Jan 23 12:07:21 PST 2016
Total Time: 1 seconds (0.01 minutes) (0.0 hours)

**Comment by er1c** [comment]
grr one of the tests is borked

**Comment by er1c** [comment]
PR Updated, tests & all passing

**Pull request closed without merging**
